# CircleCI configuration file
version: 2.1

orbs:
  python: circleci/python:3.9
  
jobs:
  build:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - run: python --version
          
      - run:
          name: install dependencies
          command: make install

      - run:
          name: Run tests
          command: python -m pytest
      
     - run: # echo "Say hello to YAML!"
         name: run lint
         command: make lint

workflows:
  build_and_test-workflow:
    jobs:
      - build_and_test
