# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  say_hello:
    docker:
     - image: cimg/base:2022.05
    working_directory : ~/repo
    
    steps:
     - checkout
     
     - run: # echo "Say hello to YAML!"
         name: install dependencies
         command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      
     - run: # echo "Say hello to YAML!"
         name: run lint
         command: |
            . venv/bin/activate
            make list

workflows:
  say-hello-workflow:
    jobs:
      - say_hello

